### PR TITLE
Fix core #314 - Use windows default CAs for tls client connections

### LINKED ISSUE #314: cli_wallet -s wss://{ANY VALID AUTHORITY}/ws fails with 'TLS handshake failed'
The `cli_wallet.exe` binary part of build BitShares Core Release 2.0.170606 Windows binaries package, fails with **TLS handshake failed** message when attempting to connect to any wss server. 

Attempts have been made against a number of the `wss://` uri's listed in the lightweight client as well as the `wss://` uri documented in the tutorial: `wss://bitshares.openledger.info/ws`

The full output from the `cli_wallet.exe` is posted below (note; the executable has been run in an Administrative level command prompt).

`C:\Temp\bitshares-cli>cli_wallet -s wss://bitshares.openledger.info/ws`
`Logging RPC to file: logs\rpc\rpc.log`
`1626215ms th_a       main.cpp:120                  main                 ] key_to_wif( committee_private_key ): 5KCBDTcyDqzsqehcb52tW5nU6pXife6V2rX9Yf7c3saYSzbDZ5W`
`1626215ms th_a       main.cpp:124                  main                 ] nathan_pub_key: BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV`
`1626215ms th_a       main.cpp:125                  main                 ] key_to_wif( nathan_private_key ): 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3`
`Starting a new wallet with chain ID 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 (from egenesis)`
`1626231ms th_a       main.cpp:172                  main                 ] wdata.ws_server: wss://bitshares.openledger.info/ws`
`0 exception: unspecified`
`TLS handshake failed`
`    {"message":"TLS handshake failed"}`
`    asio  websocket.cpp:518 fc::http::detail::websocket_tls_client_impl::{ctor}::<lambda_79cc34a518286825a5be07605053c212>::operator ()`

`    {"uri":"wss://bitshares.openledger.info/ws"}`
`    th_a  websocket.cpp:704 fc::http::websocket_client::secure_connect`

`    {"uri":"wss://bitshares.openledger.info/ws"}`
`    th_a  websocket.cpp:678 fc::http::websocket_client::connect`

`C:\Temp\bitshares-cli>`
  
Second issue; in addition, the output (above) indicates that a `logs\rpc\rpc.log` file is created but this file/folder does not exist relative to the the directory from which `cli_wallet.exe` is executed. A search across the entire file-system of the server which the `cli_wallet.exe` is being executed on does not locate an `rpc.log` file anywhere. 

Please check that the `rpc.log` file indicated in the output is being generated and if it is, provide the fully qualified path in which it is located.

### PR DESCRIPTION
**Pull request by pmconrad**
Fixes https://github.com/bitshares/bitshares-core/issues/314

Tested with mingw32 cross-build.

### CODE REVIEW

**Comment by pmconrad** [comment]
Note: this fix only fixes it for windows.

@jmjatlanta I have found hints how to do it properly on mac, but no code snippets. Perhaps you want to try? :-) https://stackoverflow.com/a/19612161

**Comment by jmjatlanta** [comment]
Very nice find. I will put something together and test it out.

**Review by jmjatlanta — APPROVED** [review]
I have confirmed this fix works on Windows. Previous to this, unable to connect without the environment variable set. Now, able to connect without setting the variable. Good job! Will attempt something similar for macOS.

Update: It will be difficult for me to test, as my mac works without any changes. I say we don't attempt to fix on mac until someone says it is a problem (I kinda doubt it is).

**Comment by pmconrad** [comment]
I suppose it works on yours because you have openssl installed.
There are various ways to make it work, centering around creating a CA file in the appropriate place.
The proper fix would be to validate certificates against the native key store, as this fix does for windows.
Leaving it as-is is a valid option I think. I doubt there are many mac users who use cli_wallet. ;-)

**Pull request merged**
