### PR TITLE
Add Travis CI file

### PR DESCRIPTION
**Pull request by abitmore**

### CODE REVIEW

**Comment by oxarbitrage** [comment]
i was testing some travis with this pull and there are a few test cases failing that we need to fix to make the tests pass, please check https://travis-ci.org/oxarbitrage/bitshares-fc/builds/357176707

3 tests were commented out at: https://github.com/bitshares/bitshares-fc/compare/master...oxarbitrage:time_test

time test issues are by https://github.com/bitshares/bitshares-fc/pull/10/files and we have an issue to fix at https://github.com/bitshares/bitshares-core/issues/597

the rand test issue not sure what causes it.

**Comment by pmconrad** [comment]
The problem with testing randomness is that you can't expect deterministic test results. :-/
It shouldn't fail so often, though. Not sure what the reason is, but since the tested methods are more or less straightforward wrappers around openssl I suspect the test itself being wrong.
IMO just disable it.

**Comment by abitmore** [comment]
I'll submit a new PR for the websocket test fix. Leave this PR for other issues.

**Comment by oxarbitrage** [comment]
i think we can close this PR, merge https://github.com/bitshares/bitshares-fc/pull/30 and https://github.com/bitshares/bitshares-fc/pull/27 for travis and work in the websocket in new pull. 

please note pull 30 will have the initial work in websocket tests done here by @abitmore

**Comment by abitmore** [comment]
I'm OK.

**Pull request closed without merging**
