### PR TITLE
Fix core #1935

### LINKED ISSUE #1935: Build Error  error: static assertion failed: Failed to reserve enough space in fc::fwd<T,S>
**Instructions**
Please include a detailed Title above. Next, please complete the following sections below:
* Build Error
In file included from /root/bitshares-core/libraries/fc/src/network/tcp_socket.cpp:4:0:
/root/bitshares-core/libraries/fc/include/fc/fwd_impl.hpp: In instantiation of ‘void fc::check_size() [with long unsigned int RequiredSize = 96ul; long unsigned int ProvidedSize = 84ul]’:
/root/bitshares-core/libraries/fc/include/fc/fwd_impl.hpp:85:43:   required from ‘fc::fwd<T, S, Align>::fwd() [with T = fc::tcp_socket::impl; unsigned int S = 84u; Align = double]’
/root/bitshares-core/libraries/fc/src/network/tcp_socket.cpp:91:26:   required from here
/root/bitshares-core/libraries/fc/include/fc/fwd_impl.hpp:60:25: error: static assertion failed: Failed to reserve enough space in fc::fwd<T,S>
     void check_size() { static_assert( (ProvidedSize >= RequiredSize), "Failed to reserve enough space in fc::fwd<T,S>" ); }
                         ^
libraries/fc/CMakeFiles/fc.dir/build.make:816: recipe for target 'libraries/fc/CMakeFiles/fc.dir/src/network/tcp_socket.cpp.o' failed
make[2]: *** [libraries/fc/CMakeFiles/fc.dir/src/network/tcp_socket.cpp.o] Error 1
CMakeFiles/Makefile2:183: recipe for target 'libraries/fc/CMakeFiles/fc.dir/all' failed
make[1]: *** [libraries/fc/CMakeFiles/fc.dir/all] Error 2
Makefile:129: recipe for target 'all' failed 

**Build Error Description**
error: static assertion failed: Failed to reserve enough space in fc::fwd<T,S>
 my os is ubuntu 16.04
when build test-3.3.0 and test-3.3.1 , the same build error occured.

help!

### PR DESCRIPTION
**Pull request by pmconrad**
Attempt to fix https://github.com/bitshares/bitshares-core/issues/1935

### CODE REVIEW

**Comment by abitmore** [comment]
One minor issue, current release/develop branch of bitshares-core repository has FC at 91d8772b7b09819b59893d645d01fe181923693d, but current master branch of FC has new commits about OpenBSD support. Do we want to bump FC in bitshares-core to include the OpenBSD commits as well?

**Comment by pmconrad** [comment]
Hm. We have no clearly defined procedure for fc fixes during a release.
The point of working on the release branch is to uphold the feature freeze associated with entering release mode. Thus, after merging we should bump fc to 7b37cd6 instead of master.

**Comment by abitmore** [comment]
Yes, I think so as well. Perhaps create a `3.3` branch in this repository, so we can add new commits to it if needed.

By the way, `3.2.1` release's FC points to [fix-api-close branch](https://github.com/bitshares/bitshares-fc/tree/fix-api-close) in this repository. The branch is configured as protected to avoid accidental removal until next consensus release.

**Comment by pmconrad** [comment]
> By the way, 3.2.1 release's FC points to fix-api-close branch in this repository. The branch is configured as protected to avoid accidental removal until next consensus release.

Submodules never point to branch names but always to specific commits AFAIK. Removing the branch shouldn't hurt.

**Comment by abitmore** [comment]
>Removing the branch shouldn't hurt.

... as long as the commit isn't removed by GC due to potential "unreachable" state. You're correct that submodule doesn't point to a branch, I wrote "head of xx branch" at first, but forgot why removed the words when reviewing / editing. :/

**Review by abitmore — APPROVED** [review]

**Pull request merged**
