### PR TITLE
Generalize flat_set serialization templates to allow different sorting and/or allocators

### PR DESCRIPTION
**Pull request by pmconrad**
Will be helpful in replacing more ``flat_set<public_key_type>`` with more efficient sorting.

### CODE REVIEW

**Comment by jmjatlanta** [comment]
Nice addition to add flexibility. Should this PR be based on the develop branch?

Oops, this is fc, not core. Nevermind. Reviewing.

**Review by jmjatlanta — APPROVED** [review]
Code looks good. While I consider myself a variadic template novice, I attempted some tests that compiled and ran.

Compiled on Ubuntu 18.04 / Boost 1.65 / OpenSSL 1.10 and ran included tests without error.

**Review by abitmore — APPROVED** [review]
Looks good to me.

**Comment by pmconrad** [comment]
Thanks!

**Pull request merged**
