### PR TITLE
Issue 727b - A second option

### PR DESCRIPTION
**Pull request by jmjatlanta**
This is another option for adding stacktrace to bitshares. Instead of porting fc/stacktrace from steem, I pulled stacktrace from the 1.65 version of boost.

Boost has more lines of code, but code quality appears better, and is probably tested to a higher degree (more eyes on it).

### CODE REVIEW

**Review by pmconrad — CHANGES_REQUESTED** [review]
Much better than #23 IMO.
Question: is it important for us to have stacktraces for pre-1.65 boost?
I think it isn't, and therefore I'd propose to *not* copy the old boost code but instead rebase on #36 and detect boost version at compile-time and replace the stacktrace stuff with NOPs if boost is too old.

**Comment by jmjatlanta** [comment]
> Question: is it important for us to have stacktraces for pre-1.65 boost?
I think it isn't,

I agree. If everyone else does, I'll rebase on the Boost 1.66 stuff and a skip the stacktrace logic pre boost 1.65.

**Comment by pmconrad** [comment]
@abitmore ?

**Comment by abitmore** [comment]
>> Question: is it important for us to have stacktraces for pre-1.65 boost?
>>I think it isn't,
>
>I agree. If everyone else does, I'll rebase on the Boost 1.66 stuff and a skip the stacktrace logic pre boost 1.65.

I agree.

**Comment by jmjatlanta** [comment]
The rebase included commits that muddy the waters. I have created a new PR.
https://github.com/bitshares/bitshares-fc/pull/38

**Pull request closed without merging**
