### PR TITLE
use v->_type to set/get type directly

### PR DESCRIPTION
**Pull request by RichardWeiYang**
Trivial code cleanup.

### CODE REVIEW

**Comment by pmconrad** [comment]
Please explain why you think this is an improvement.

**Comment by RichardWeiYang** [comment]
In my mind, there are several advantages if we apply this commit.

1. The code access the _type field directly instead of several level of type casting
2. In the original code, audience should construct the memory layout of variant in mind and then understand this is the _type filed used to set/get the type information
3. This would be more friendly in case we are willing to modify the memory layout to have more feature in the future

Hope you would like it.

**Comment by pmconrad** [comment]
Thanks. These reasons are debatable IMO, and even if they hold the gain doesn't justify the effort required for review and/or debate. @team If you disagree feel free to reopen.

@RichardWeiYang If you want to help improve the code you might want to look at https://sonarcloud.io/organizations/flwyiq7go36p6lipr64tbesy5jayad3q/projects - there are 2.5k "Code Smells" waiting to be fixed. :-)

**Comment by RichardWeiYang** [comment]
@pmconrad

Thanks for your information. 

While I still think this is a reasonable change. @Team to reopen it?

**Pull request closed without merging**
