### PR TITLE
Modifications to run sonar-scanner during travis build

### PR DESCRIPTION
**Pull request by pmconrad**
Experimental - one known problem is that encrypted parameters in .travis.yml may not be available when building PRs from foreign repos. Like this one.

### CODE REVIEW

**Comment by oxarbitrage** [comment]
"The command "which sonar-scanner && sonar-scanner || true" exited with 0."

i think this should output an url with the report ?

**Comment by pmconrad** [comment]
> i think this should output an url with the report ?

Sonar wasn't run during that build, because the PR was created from my private repo. (It it was there should be a URL, yes.)

**Comment by pmconrad** [comment]
The script is usable for core as well, only need to adapt test invocation and `apt-get install parallel` there.

**Comment by oxarbitrage** [comment]
lets use https://github.com/bitshares/bitshares-fc/pull/49

**Pull request closed without merging**
