### PR TITLE
add check for maximum boost version

### PR DESCRIPTION
**Pull request by xloem**

### CODE REVIEW

**Comment by xloem** [comment]
I added this to make bitshares-core build more easily.  Maybe the check should go in bitshares-core, I'm not sure.

**Comment by abitmore** [comment]
I'm not sure if it's a good idea to do so, since we always look for supporting latest boost library although often we're a bit late. https://github.com/bitshares/bitshares-core/issues/2216

**Comment by xloem** [comment]
This PR would make sense if you do another release before supporting the latest version of boost.

**Comment by abitmore** [comment]
We does support boost 1.70 and probably some higher versions. See https://github.com/bitshares/bitshares-core/issues/2208. But the documentations are outdated. Fixing the documentations and adding support for higher boost versions are more productive IMHO.

**Comment by xloem** [comment]
? Doesn't https://github.com/bitshares/bitshares-core/issues/2208 say 1.70 is still on the backburner for https://github.com/bitshares/bitshares-core/issues/2216 ?  I'm still running into https://github.com/bitshares/bitshares-core/issues/1935 when I try to use boost 1.70

[edit: with bitshares-core, of course. I haven't tried building bitshares-fc in any standalone way]

maybe it would be helpful if I changed the PR to emit a warning instead of breaking the build or something

**Comment by abitmore** [comment]
You're on Windows? It seems https://github.com/bitshares/bitshares-fc/pull/150 only fixed non-Windows build.

**Comment by abitmore** [comment]
Yeah, a warning would be better. Thanks.

**Comment by xloem** [comment]
I'm actually on RHEL7 with a manually built boost.  I'm looking at the cause of the error.

I'm thinking the correct solution to this error would be to move the declaration of `impl` classes into header files, so the compiler can calculate their size itself.  The problem is that compilers are allowed to arbitrarily pad classes for alignment or runtime debugging information or whatnot, so hardcoding their size would be advised against.  What do you think of that idea?

I'm going to try coding up a quicker and simpler fix that changes the hardcoded number to a sum of sizeof() calls, just for this one instance, and submit that as a PR unless I hear more from you.

I see this PR is not the correct solution here.

**Comment by xloem** [comment]
```
bitshares-core/libraries/fc/include/fc/fwd_impl.hpp: In instantiation of ‘void fc::check_size() [with long unsigned int RequiredSize = 80; long unsigned int ProvidedSize = 72]’:
bitshares-core/libraries/fc/include/fc/fwd_impl.hpp:85:43:   required from ‘fc::fwd<T, S, Align>::fwd() [with T = fc::tcp_socket::impl; unsigned int S = 72; Align = double]’
bitshares-core/libraries/fc/src/network/tcp_socket.cpp:98:26:   required from here
```

**Comment by xloem** [comment]
To close this out, wiping my build folder resolved this issue for me.

If the sizeof approach is ever of interest, here was the change I had prepared.  It's just the size of a pointer for the vtable if there are virtual functions, plus the size of every member:
```
diff --git a/include/fc/network/tcp_socket.hpp b/include/fc/network/tcp_socket.hpp
index 6e69f80..4f38da0 100644
--- a/include/fc/network/tcp_socket.hpp
+++ b/include/fc/network/tcp_socket.hpp
@@ -3,6 +3,9 @@
 #include <fc/io/iostream.hpp>
 #include <fc/time.hpp>
 
+#include <fc/asio.hpp>
+#include <fc/thread/future.hpp>
+
 namespace fc {
   namespace ip { class endpoint; }
 
@@ -52,11 +55,7 @@ namespace fc {
     private:
       friend class tcp_server;
       class impl;
-      #ifdef _WIN64
-      fc::fwd<impl,0xa8> my;
-      #else
-      fc::fwd<impl,0x60> my;
-      #endif
+      fc::fwd<impl,sizeof(void* /*vtable*/)+sizeof(fc::future<size_t>)*2+sizeof(boost::asio::ip::tcp::socket)+sizeof(tcp_socket_io_hooks*)> my;
   };
   typedef std::shared_ptr<tcp_socket> tcp_socket_ptr;
```

**Comment by abitmore** [comment]
Yes, the `sizeof` approach is in my mind and it should fix the issue so we don't need to modify the value every time in the future. I just haven't got time to try it out. If your code works please feel free to create a PR. Thanks.

Update:
I think the `impl` class declared here was meant to hide the implementation details, perhaps for smaller binary file or whatever. But it seems the `sizeof` calculation is not serving the same purpose? What do you think?

**Pull request closed without merging**
