### PR TITLE
fix incorrect project_editline-build path

### PR DESCRIPTION
**Pull request by ihla**

### CODE REVIEW

**Comment by abitmore** [comment]
I think this change will break normal build.

**Comment by ihla** [comment]
tested with cmake && make also and works

**Comment by abitmore** [comment]
I don't remember why I added a `src/` in [line 146](https://github.com/bitshares/bitshares-fc/commit/5f6e4d852339e8fab5991d81edc57f26971929c2#diff-af3b638bc2a3e6c650974192a53c7291R146) in the first place, just remember that I failed to build without it. Ideally `src` should not be in path of binaries.

**Review by abitmore — APPROVED** [review]
Looks like last time I encountered similar issue as you're solving now, just for different building platform. Ninja is using the 2 lines or one of them you've changed now, but not another line I've changed. And the 2 lines you've changed aren't being used by normal build under Ubuntu.

This PR is OK to me.

**Comment by jmjatlanta** [comment]
Question: Has this been tested beyond compilation? If the cli_wallet can't find the library, it should still compile, but with reduced functionality. I'd like the added functionality to be there if possible (i.e. tab completion, arrow key history)

**Comment by abitmore** [comment]
@jmjatlanta not like `readline`, the build process now knows whether `editline` is available, actually it's always available if done compilation. See https://github.com/bitshares/bitshares-fc/blob/6dc06cd59822c496cebad281663bf6a08900e082/CMakeLists.txt#L305-L306.

By the way, github now shows linked code in comments directly, convenient.

**Pull request merged**
