### PR TITLE
Modifications to run sonar-scanner during travis build

### PR DESCRIPTION
**Pull request by pmconrad**
This PR is mostly identical to #46, the only difference being that it is an internal PR (i. e. from a branch inside this repo, while the other is from by private repo).
Sonar-scanner should be executed for the PR (it was already executed when I pushed the branch to this repo, but should be run separately for the PR).

### CODE REVIEW

**Comment by pmconrad** [comment]
https://sonarcloud.io/project/branches?id=BitShares-FC

**Comment by oxarbitrage** [comment]
when i click the link i get redirected to a login screen. when i select github it goes briefly to the repo inside sonar but  immediately back to the login page. seems an auth issue. @pmconrad you maybe need to add others to have access? if so, please add me.

**Comment by pmconrad** [comment]
Hm, perhaps try this link: https://sonarcloud.io/dashboard?id=BitShares-FC

**Review by oxarbitrage — APPROVED** [review]
thanks. looks good. lets keep testing it merged into `master`.

**Pull request merged**
