### PR TITLE
RPC logging level inconsistency #929

### PR DESCRIPTION
**Pull request by cogutvalera**
https://github.com/bitshares/bitshares-core/issues/929

### CODE REVIEW

**Review by abitmore — DISMISSED** [review]
Good job.

**Comment by cogutvalera** [comment]
@abitmore Thank you very much !

**Comment by cogutvalera** [comment]
should I close this pull request ? or not ?

**Review by pmconrad — CHANGES_REQUESTED** [review]
Also need to add this to websocket_tls_server_impl.
Please check for other places as well.

**Comment by pmconrad** [comment]
> should I close this pull request ? or not ?

Just keep it open until we have merged it.

**Comment by cogutvalera** [comment]
> Just keep it open until we have merged it.

OK. Sure ! Thx !

> Also need to add this to websocket_tls_server_impl.
> Please check for other places as well.

OK. I will check.

**Comment by cogutvalera** [comment]
@pmconrad I've added log for websocket_tls_server_impl but cannot find other places.

**Comment by cogutvalera** [comment]
I don't see any other places for logs, is this issue finished or not yet ? Should I do any changes here or not ?

**Review by pmconrad — APPROVED** [review]

**Comment by nanomobile** [comment]
Thanks !

**Pull request merged**
