### PR TITLE
Increase stack depth for boost v1.74.0

### PR DESCRIPTION
**Pull request by philmb3487**
Increase the stack depth to 11 for the new boost releases.

Here is the stack log: -------

[stack.txt](https://github.com/bitshares/bitshares-fc/files/5791526/stack.txt)

### CODE REVIEW

**Comment by philmb3487** [comment]
I need to rework the patch a bit, it's actually 12.  Not 11.

**Comment by philmb3487** [comment]
Ready to go.

> *** No errors detected

**Comment by abitmore** [comment]
Thanks. It seems it's another issue related to https://github.com/bitshares/bitshares-core/issues/2216. Will setup CI and test (may need some time due to priority, please be patient).

**Review by abitmore — APPROVED** [review]
Thanks.

**Pull request merged**
