### PR TITLE
remove WITH_EXOTIC_JSON_PARSERS

### PR DESCRIPTION
**Pull request by oxarbitrage**
reverse https://github.com/bitshares/bitshares-fc/commit/1ae3cc2fad06aa17bdaf1f5fc7713df0a1f24c92

needed for https://github.com/bitshares/bitshares-core/pull/1356

### CODE REVIEW

**Comment by pmconrad** [comment]
I think you shouldn't remove it completely but only re-enable what you need.
Also, I thought you were only generating JSON not parsing it?

**Comment by oxarbitrage** [comment]
the only thing i actually need is to use the `fc::json::legacy_generator` here: https://github.com/bitshares/bitshares-core/blob/ee605c360aab9c3a8d97618ee8541967376866d6/libraries/plugins/elasticsearch/elasticsearch_plugin.cpp#L326

**Comment by abitmore** [comment]
IMHO adding another option to `enum output_formatting` other than `stringify_large_ints_and_doubles`, e.g. `no_stringfy`, then the plugin would work.

**Comment by oxarbitrage** [comment]
by applying only this change the plugin will work: https://github.com/bitshares/bitshares-fc/pull/80/files

**Review by pmconrad — APPROVED** [review]

**Pull request merged**
