### PR TITLE
Remove custom FindBoost.cmake

### PR DESCRIPTION
**Pull request by jmjatlanta**
A custom FindBoost.cmake was added to resolve a v2.x version cmake bug. We now only support cmake 3.2 and above, so the extra steps included are no longer necessary.

### CODE REVIEW

**Comment by jmjatlanta** [comment]
travis is complaining. It works on my 16.04 and 18.04 Ubuntu boxes. I am attempting to find out what is going on.

**Comment by pmconrad** [comment]
Getting the same error locally. Apparently `-lpthread` is missing on the linker command line.

**Comment by jmjatlanta** [comment]
> Getting the same error locally. Apparently `-lpthread` is missing on the linker command line.

That stinks. From what I read, they fixed an issue with that back in the 2.x versions of cmake. I guess it crept up again. What version of cmake are you using?

**Comment by pmconrad** [comment]
`cmake version 3.10.2`

With my last commit here it works again. Apparently removing BoostConfig was too much.

**Review by oxarbitrage — APPROVED** [review]
looks good.

**Pull request merged**
